name: Generate Podcast Feeds
on: [push]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Run Feed Generator
        uses: nfrankel/podcast-generator@master
